### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in Wiki USD scan example

### ISSUE THREAD

**Issue by DePierre** [eik00d/CANToolz#93]
In the Wiki example https://github.com/eik00d/CANToolz/wiki/uds_scan, the CANToolz configuration contains an error (I suppose the code was updated since the configuration was first created).

Having `sub` set to `None` will trigger an exception in the module `gen_ping`.

Using:
```python
  {'gen_ping':    {                    # Generate UDS requests
      'pipe': 2,
      'delay': 0.06,
      'range': [1, 2047],           # ID range (from 1790 to 1794)
      'services':[{'service': 0x10, 'sub': 0x01},
                {'service': 0x3E, 'sub': None},
                {'service': 0x3E, 'sub': 0x01}],
      'mode':'UDS'}
  },
```

Will raise the following exception:
```pytb
Traceback (most recent call last):
  File "cantoolz.py", line 172, in do_GET
    modz = self.can_engine.start_loop()
  File "/CANToolz/cantoolz/engine.py", line 114, in start_loop
    module.do_start(params)
  File "/CANToolz/cantoolz/modules/gen_ping.py", line 106, in do_start
    for sb in sub:
TypeError: 'NoneType' object is not iterable
```

**Comment by eik00d** [comment]
Thx! Will fix this week!

**Comment by eik00d** [comment]
Fixed on 'trunk' for now. https://github.com/eik00d/CANToolz/tree/trunk
